# Generated by Django 4.1 on 2022-12-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_options_comment_login_require'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='login_require',
        ),
        migrations.AddField(
            model_name='post',
            name='login_require',
            field=models.BooleanField(default=False),
        ),
    ]
